# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vv3bxj_KaC09TtoMEOOREs2_0O76xJ3

1 - Utilize o comando 'input' para receber ao menos 2 números de entrada do usuário

2 - Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);


3- Implemente ao menos 4 operações matemáticas em seu código;


4- Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;

5- Utilize o comando 'print' para exibir o resultado da operação matemática.
"""

valor1 = int(input("Digite o valor 1 : "))
valor2 = int(input("Digite o valor 2: "))

operacao = input('Selecione uma operação para realizar com os valores informados : +, -, * ou / :')

if operacao == '+' :
    print('A Soma dos valores é : ',valor1 + valor2) # Adição
elif operacao == '-':
    print('A Subtração dos valores é : ',valor1 - valor2) # Subtração
elif operacao == '*':
    print('A Multiplicação dos valores é : ', valor1 * valor2) # Multiplicação
elif operacao == '/':
    print('A divisão dos valores é : ', valor1/valor2)  # Divisão
else:
    print('Operação inválida')